/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AgentsSplatRouteImport } from './routes/agents/$'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as OrganizationsRefIndexRouteImport } from './routes/organizations/$ref/index'
import { Route as OrganizationsRefAgentsIndexRouteImport } from './routes/organizations/$ref/agents/index'
import { Route as OrganizationsRefAgentsAgentRefRouteImport } from './routes/organizations/$ref/agents/$agentRef'
import { Route as OrganizationsRefAgentsNewRouteImport } from './routes/organizations/$ref/agents/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSplatRoute = AgentsSplatRouteImport.update({
  id: '/agents/$',
  path: '/agents/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRefIndexRoute = OrganizationsRefIndexRouteImport.update({
  id: '/organizations/$ref/',
  path: '/organizations/$ref/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRefAgentsIndexRoute =
  OrganizationsRefAgentsIndexRouteImport.update({
    id: '/organizations/$ref/agents/',
    path: '/organizations/$ref/agents/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsRefAgentsAgentRefRoute =
  OrganizationsRefAgentsAgentRefRouteImport.update({
    id: '/organizations/$ref/agents/$agentRef',
    path: '/organizations/$ref/agents/$agentRef',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsRefAgentsNewRoute =
  OrganizationsRefAgentsNewRouteImport.update({
    id: '/organizations/$ref/agents/new',
    path: '/organizations/$ref/agents/new',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents/$': typeof AgentsSplatRoute
  '/agents/': typeof AgentsIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/organizations/$ref/': typeof OrganizationsRefIndexRoute
  '/organizations/$ref/agents/$agentRef': typeof OrganizationsRefAgentsAgentRefRoute
  '/organizations/$ref/agents/new': typeof OrganizationsRefAgentsNewRoute
  '/organizations/$ref/agents/': typeof OrganizationsRefAgentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents/$': typeof AgentsSplatRoute
  '/agents': typeof AgentsIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/organizations/$ref': typeof OrganizationsRefIndexRoute
  '/organizations/$ref/agents/$agentRef': typeof OrganizationsRefAgentsAgentRefRoute
  '/organizations/$ref/agents/new': typeof OrganizationsRefAgentsNewRoute
  '/organizations/$ref/agents': typeof OrganizationsRefAgentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents/$': typeof AgentsSplatRoute
  '/agents/': typeof AgentsIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/organizations/$ref/': typeof OrganizationsRefIndexRoute
  '/organizations/$ref/agents/$agentRef': typeof OrganizationsRefAgentsAgentRefRoute
  '/organizations/$ref/agents/new': typeof OrganizationsRefAgentsNewRoute
  '/organizations/$ref/agents/': typeof OrganizationsRefAgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents/$'
    | '/agents/'
    | '/organizations/'
    | '/organizations/$ref/'
    | '/organizations/$ref/agents/$agentRef'
    | '/organizations/$ref/agents/new'
    | '/organizations/$ref/agents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents/$'
    | '/agents'
    | '/organizations'
    | '/organizations/$ref'
    | '/organizations/$ref/agents/$agentRef'
    | '/organizations/$ref/agents/new'
    | '/organizations/$ref/agents'
  id:
    | '__root__'
    | '/'
    | '/agents/$'
    | '/agents/'
    | '/organizations/'
    | '/organizations/$ref/'
    | '/organizations/$ref/agents/$agentRef'
    | '/organizations/$ref/agents/new'
    | '/organizations/$ref/agents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsSplatRoute: typeof AgentsSplatRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  OrganizationsRefIndexRoute: typeof OrganizationsRefIndexRoute
  OrganizationsRefAgentsAgentRefRoute: typeof OrganizationsRefAgentsAgentRefRoute
  OrganizationsRefAgentsNewRoute: typeof OrganizationsRefAgentsNewRoute
  OrganizationsRefAgentsIndexRoute: typeof OrganizationsRefAgentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$': {
      id: '/agents/$'
      path: '/agents/$'
      fullPath: '/agents/$'
      preLoaderRoute: typeof AgentsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$ref/': {
      id: '/organizations/$ref/'
      path: '/organizations/$ref'
      fullPath: '/organizations/$ref/'
      preLoaderRoute: typeof OrganizationsRefIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$ref/agents/': {
      id: '/organizations/$ref/agents/'
      path: '/organizations/$ref/agents'
      fullPath: '/organizations/$ref/agents/'
      preLoaderRoute: typeof OrganizationsRefAgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$ref/agents/$agentRef': {
      id: '/organizations/$ref/agents/$agentRef'
      path: '/organizations/$ref/agents/$agentRef'
      fullPath: '/organizations/$ref/agents/$agentRef'
      preLoaderRoute: typeof OrganizationsRefAgentsAgentRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$ref/agents/new': {
      id: '/organizations/$ref/agents/new'
      path: '/organizations/$ref/agents/new'
      fullPath: '/organizations/$ref/agents/new'
      preLoaderRoute: typeof OrganizationsRefAgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsSplatRoute: AgentsSplatRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  OrganizationsRefIndexRoute: OrganizationsRefIndexRoute,
  OrganizationsRefAgentsAgentRefRoute: OrganizationsRefAgentsAgentRefRoute,
  OrganizationsRefAgentsNewRoute: OrganizationsRefAgentsNewRoute,
  OrganizationsRefAgentsIndexRoute: OrganizationsRefAgentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
