// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Mharrech Ayoub <mharrech.ayoub@gmail.com>

// GENERATED FILE — do not edit.
// Source: packages/skills-catalogue/catalogue/<category>/<slug>/SKILL.md
// Regenerate with: pnpm --filter @agentco/skills-catalogue build:catalogue

export type CatalogueSource = {
  slug: string;
  category: string;
  markdown: string;
};

export const CATALOGUE_SOURCES: CatalogueSource[] = [
  {
    slug: "metrics-and-dashboards",
    category: "data",
    markdown: "---\nname: metrics-and-dashboards\ndescription: Choose metrics that drive decisions and build dashboards people read. Use when defining KPIs, building a dashboard, or when reporting is ignored.\nrecommendedForRoles:\n  - pm\n  - cfo\n  - ceo\n  - researcher\ntags:\n  - metrics\n  - data\n  - reporting\n---\n\n# Metrics and dashboards\n\nA dashboard nobody acts on is a cost with no benefit.\n\n## When to use\n\nDefining what to measure, or building a view somebody will look at regularly.\n\n## Choosing a metric\n\n- **Tie it to a decision.** If no plausible value would change what anybody does,\n  do not track it on a dashboard. Put it in a report nobody has to look at.\n- **Prefer rates and ratios to totals.** Totals go up because time passes.\n- **Pair every metric with its counterweight.** Speed with quality, growth with\n  retention, volume with cost. A single metric optimised alone is always gamed,\n  usually unintentionally.\n- **Beware vanity.** Page views, signups, raw counts. They rise reliably and mean\n  little on their own.\n\n## Define it once\n\nWrite the definition down: what is counted, what is excluded, which timezone,\nwhich timestamp. Then use that definition everywhere. Two dashboards showing\ndifferent numbers for the same word is how people stop believing all of them.\n\n## Building the view\n\n- **One question per screen.** Name it in the title.\n- **One headline number**, large, with the comparison that gives it meaning —\n  against last period, against target. A number alone is not information.\n- **Show the trend**, not just today. A point tells you nothing about direction.\n- **Four figures at most** competing for attention. Past that there is no headline\n  and the eye has nowhere to land.\n- **Label what \"good\" is.** A reader who cannot tell whether 68 is good learns\n  nothing from being shown it.\n\n## Maintain it\n\nReview dashboards periodically and delete the panels nobody looks at. An\nabandoned dashboard is worse than none, because someone will eventually trust it.\n",
  },
  {
    slug: "sql-analysis",
    category: "data",
    markdown: "---\nname: sql-analysis\ndescription: Answer a question with SQL and be confident the answer is right. Use when asked for a number, a breakdown, or a trend from a database.\nrecommendedForRoles:\n  - researcher\n  - engineer\n  - pm\n  - cfo\ntags:\n  - sql\n  - data\n  - analysis\n---\n\n# SQL analysis\n\nThe difficulty is almost never the SQL. It is knowing whether the number means\nwhat somebody thinks it means.\n\n## When to use\n\nProducing a figure, a breakdown or a trend from a database.\n\n## Before writing the query\n\n- **What exactly is being asked?** \"How many users\" — active when? Including\n  deleted? Counting accounts or people? Getting this wrong produces a confident,\n  precise, wrong answer.\n- **What does the table actually contain?** Look at a few rows. Check for soft\n  deletes, test accounts, duplicate rows, nulls where you expect values, and the\n  timezone the timestamps are in.\n\n## Writing it\n\n- Filter out test and internal accounts, explicitly. They are almost never what\n  the asker means.\n- Be precise about time boundaries and say which timezone. \"Last month\" is\n  ambiguous and the difference is often material.\n- Beware `JOIN` fan-out: joining to a one-to-many table multiplies rows, and\n  every `SUM` after it is wrong. Aggregate first, then join.\n- `COUNT(column)` skips nulls; `COUNT(*)` does not. This is a common silent error.\n- `LEFT JOIN` followed by a `WHERE` on the right-hand table is an inner join.\n\n## Check it\n\n- Compute it a second way and compare. Different shapes agreeing is real evidence.\n- Check the total against something known.\n- Look at the extremes. The largest and smallest rows expose bad joins and stray\n  test data immediately.\n- Sanity-check the magnitude. A number ten times what anybody expected is usually\n  a fan-out, not a discovery.\n\n## Report it\n\nGive the number, the definition you used, the period, and what you excluded. A\nfigure without its definition will be compared against a differently-defined one\nwithin the week.\n",
  },
  {
    slug: "design-systems",
    category: "design",
    markdown: "---\nname: design-systems\ndescription: Keep an interface consistent by building from shared tokens and components. Use when adding UI, reviewing visual work, or a product has started to look assembled from parts.\nrecommendedForRoles:\n  - designer\n  - engineer\ntags:\n  - design\n  - frontend\n  - consistency\n---\n\n# Design systems\n\nConsistency is not an aesthetic preference. It is what lets somebody learn a\nproduct once instead of every screen.\n\n## When to use\n\nAdding a new screen or component, or reviewing UI that has drifted.\n\n## Tokens before components\n\nDecide the small set once — colour, spacing, radius, type scale, shadow — and\nname them by role rather than by value. `--surface` and `--danger`, not `--grey-2`\nand `--red-500`: a role survives a rebrand, a value does not.\n\nNever write a raw value in a component. The moment one component has its own\nshade of grey, there are two systems.\n\n## Colour carries meaning\n\nPick a rule and hold it. A good one: colour means state — active, needs\nattention, failed, idle — and nothing else. Brand marks are the documented\nexception. Under that rule a coloured element is always informative, and somebody\ncan scan a dense screen and see only what matters.\n\n## Components\n\nBefore building one, check whether it exists. Two date pickers is not twice the\ncapability, it is twice the maintenance and two behaviours to learn.\n\nA component owns its states — default, hover, focus, active, disabled, loading,\nerror — so no caller has to invent them. A component that cannot show its own\nloading state will be wrapped in a bespoke one at every call site.\n\n## Reviewing for drift\n\nLook for: a hard-coded colour or spacing value, a one-off component duplicating\nan existing one, the same concept with two names, a control with no visible focus\nstate, and text below the contrast threshold.\n",
  },
  {
    slug: "interface-copy",
    category: "design",
    markdown: "---\nname: interface-copy\ndescription: Write the words inside a product so people know what will happen. Use when naming buttons, writing errors, empty states, or any user-facing text.\nrecommendedForRoles:\n  - designer\n  - pm\n  - cmo\n  - general\ntags:\n  - writing\n  - ux\n  - design\n---\n\n# Interface copy\n\nWords in a product are not decoration. They are the signposting people navigate by.\n\n## When to use\n\nNaming anything, writing an error, an empty state, a confirmation, or a tooltip.\n\n## Principles\n\n- **Name things as users understand them**, not as the system is built. Somebody\n  manages notifications; they do not configure a webhook.\n- **A button says what happens.** \"Save changes\", not \"Submit\". \"Delete project\",\n  not \"OK\".\n- **Keep the word through the whole flow.** The button that says Publish produces\n  a message that says Published. Changing the word makes people wonder whether\n  something different happened.\n- **Sentence case, plain verbs, no filler.** Cut \"please\", \"simply\", \"just\" and\n  \"in order to\".\n\n## Errors\n\nSay what went wrong, and what to do about it. Never apologise, never be vague.\n\n- Bad: \"Something went wrong.\"\n- Better: \"We couldn't save that. Check your connection and try again.\"\n- Best: \"That slug is already used by another project. Pick a different one.\"\n\nAn error that names the field and the rule saves a support conversation.\n\n## Empty states\n\nAn empty screen is an invitation, not an absence. Say what belongs there, why it\nis useful, and give the action that fills it. \"No data\" is a wasted screen.\n\n## Destructive confirmations\n\nSay exactly what will be lost and whether it can be undone. \"Are you sure?\" gives\nsomebody nothing to be sure about. Put the consequence in the sentence and the\nverb in the button.\n",
  },
  {
    slug: "ux-review",
    category: "design",
    markdown: "---\nname: ux-review\ndescription: Review an interface for whether an ordinary person can use it. Use when reviewing a screen, a flow, or a design before it is built.\nrecommendedForRoles:\n  - designer\n  - pm\n  - engineer\ntags:\n  - ux\n  - design\n  - review\n---\n\n# UX review\n\nRead the screen as the least technical person who would ever open it: five\nminutes, once a week, with one question.\n\n## When to use\n\nReviewing any interface — a design, a built screen, or a flow end to end.\n\n## Name the question first\n\nWhat is the one thing somebody opens this to find out or to do? Write it down.\nEverything on the screen either serves that question or is in the way.\n\n## Then count, literally\n\n- **Competing numbers.** More than about four figures of equal weight and the\n  screen has no headline. Which one is the answer?\n- **Status vocabularies.** Two scales that disagree — the same value reading\n  \"Good\" here and \"Okay\" there — is a defect, not a matter of taste. One scale,\n  defined once.\n- **Duplicate blocks.** Two cards making the same point, two controls driving the\n  same variable.\n- **Jargon.** Anything a new user would have to look up. Rewrite it or explain it\n  in place.\n- **Name drift.** The heading, the navigation item, the button and the\n  documentation must call the thing the same word.\n\n## The states nobody designs\n\nCheck all five: loading, empty, one item, very many items, error. Empty and error\nare where most interfaces fall apart, and they are the states a new user sees\nfirst. An empty screen should say what goes there and how to put something there.\n\n## Say what to change\n\nFor each finding: what a person would misunderstand, and the smallest change that\nfixes it. Order by how many people hit it and how badly. \"This feels cluttered\"\nis not actionable; \"these four numbers compete and the second is the one people\ncame for\" is.\n",
  },
  {
    slug: "api-design",
    category: "engineering",
    markdown: "---\nname: api-design\ndescription: Design an HTTP API that is predictable and hard to misuse. Use when adding endpoints, changing a response shape, or reviewing an interface.\nrecommendedForRoles:\n  - engineer\n  - cto\ntags:\n  - api\n  - design\n---\n\n# API design\n\nAn API is a promise. The cost of breaking it is paid by everyone who believed it.\n\n## Shape\n\n- **Resources, not actions.** `POST /orders` rather than `POST /createOrder`.\n  Where a verb is genuinely the thing — archive, cancel, invoke — hang it off\n  the resource: `POST /orders/:id/cancel`.\n- **Use the method's meaning.** GET never changes anything. PUT replaces the\n  whole thing. PATCH changes named fields. POST creates, or does the thing a verb\n  route names.\n- **One representation.** The object a list returns should be the object a fetch\n  returns. A client that has to handle two shapes for one thing will get it wrong.\n\n## Status codes people can act on\n\n- `201` with the created object, not `200` with an id.\n- `409` for a conflict with the current state; say what the conflict is.\n- `422` for input that parsed but is not acceptable; name the field.\n- `404` rather than `403` for a resource in another tenant — a 403 confirms it\n  exists.\n- `429` when a limit was hit, and say which one.\n\n## Errors\n\nReturn a stable machine code and a sentence a person can read. The sentence is\nnot decoration: a caller given only a number retries the same request.\n\n```json\n{ \"error\": { \"code\": \"ORDER_ALREADY_SHIPPED\", \"message\": \"That order shipped on 3 June and cannot be changed.\", \"detail\": { \"shippedAt\": \"...\" } } }\n```\n\n## Paging\n\nUse a keyset cursor, not an offset. Offsets skip and repeat rows when the table\nis written to between requests. Put only the row identifier in the cursor and\nread the sort key back from the row — a timestamp round-tripped through JSON\nloses precision and drops rows at page boundaries.\n\n## Changing an existing API\n\nAdd fields; do not remove or repurpose them. Widen what you accept before you\nnarrow what you return. When something must break, version the route rather than\nchanging the meaning of an existing one.\n",
  },
  {
    slug: "code-review",
    category: "engineering",
    markdown: "---\nname: code-review\ndescription: Review a change for correctness, security and test coverage before it ships. Use when reading a diff, a pull request, or work another agent has submitted.\nrecommendedForRoles:\n  - engineer\n  - cto\n  - qa\ntags:\n  - review\n  - quality\n---\n\n# Code review\n\nFind the defects that matter. Everything else is noise.\n\n## Read the change in this order\n\n1. **What is it trying to do?** If you cannot say in one sentence, the change is\n   doing too much — say that first, before anything else.\n2. **Does it do that?** Follow the actual control flow. Do not assume a function\n   does what its name says.\n3. **What else does it do?** Unrelated edits hidden in a large diff are where\n   regressions live.\n4. **What did it not change?** A fix with no test, a new branch with no error\n   path, a renamed field with one caller left behind.\n\n## What counts as a finding\n\nReport something only if you can name the input that breaks it and the wrong\nresult it produces. \"This could be cleaner\" is not a finding. \"An empty array\nhere divides by zero\" is.\n\nRank by what it costs:\n\n- **Correctness** — wrong output, lost data, a crash on ordinary input.\n- **Security** — unvalidated input reaching a query, a secret in a log, a\n  missing authorisation check, a 403 where a 404 is needed.\n- **Concurrency** — a read followed by a write that assumes nothing happened in\n  between; anything that would break if the function ran twice at once.\n- **Error paths** — what happens when the call fails, times out, or half-succeeds.\n- **Tests** — a bug fixed without a test is a bug scheduled to return.\n\n## Before reporting\n\nVerify each finding against the code as it is now, not as you remember it. Most\nreview findings that turn out to be wrong are stale — the thing was handled three\nlines further down.\n\n## Say it usefully\n\nFor each finding: the file and line, the input that triggers it, the result, and\nthe smallest change that fixes it. Order most serious first. If you found\nnothing serious, say so plainly rather than padding with style notes.\n",
  },
  {
    slug: "database-migrations",
    category: "engineering",
    markdown: "---\nname: database-migrations\ndescription: Change a database schema without downtime or lost data. Use when adding, altering or removing columns, tables or indexes on a live system.\nrecommendedForRoles:\n  - engineer\n  - devops\n  - cto\ntags:\n  - database\n  - operations\n---\n\n# Database migrations\n\nThe old code and the new code will run at the same time. Every migration has to\nbe safe for both.\n\n## Expand, migrate, contract\n\nNever change a column in place. Three deployments:\n\n1. **Expand** — add the new column, nullable, with no constraint. Deploy code\n   that writes both old and new and reads the old.\n2. **Migrate** — backfill in batches. Deploy code that reads the new column.\n3. **Contract** — once nothing reads the old column, drop it.\n\nEach step is independently deployable and independently reversible. Skipping the\nmiddle one is how a deploy takes the site down.\n\n## Operations that lock\n\nKnow which ones take a lock that blocks writes on your database, and how long it\nholds for on a table of your size. On PostgreSQL:\n\n- Adding a nullable column with no default is cheap.\n- Adding `NOT NULL` to an existing column rewrites the table unless you add a\n  validated check constraint first.\n- Creating an index blocks writes unless you build it `CONCURRENTLY`.\n- Changing a column type usually rewrites the table.\n\nTest the migration against a copy of production-sized data, not an empty\ndevelopment database. The difference between one second and forty minutes only\nappears at scale.\n\n## Backfills\n\nBatch them. A single `UPDATE` over ten million rows holds one transaction open\nfor the whole run, bloats the table, and cannot be interrupted. Loop over ranges\nof the primary key, commit each batch, and make the loop resumable.\n\n## Always\n\n- Write the down migration, and try it.\n- Never destroy data in the same deploy that stops using it. Leave a gap long\n  enough to notice a mistake.\n- Constraints and indexes are the cheapest correctness you will ever buy. Prefer\n  a unique index to a check in application code: only the index sees both sides\n  of a race.\n",
  },
  {
    slug: "debugging",
    category: "engineering",
    markdown: "---\nname: debugging\ndescription: Find the true cause of a defect and prove the fix. Use when something behaves wrongly and the reason is not yet known.\nrecommendedForRoles:\n  - engineer\n  - qa\ntags:\n  - debugging\n  - quality\n---\n\n# Debugging\n\nThe goal is not to make the symptom disappear. It is to know why it happened.\n\n## Order of work\n\n1. **Reproduce it.** A defect you cannot reproduce is a defect you cannot know\n   you have fixed. Write down the exact steps and the exact wrong result. If it\n   only happens sometimes, find what differs between the times it does and does not.\n2. **Narrow it.** Cut the reproduction down until removing anything else makes it\n   stop. Bisect: by input, by code path, by commit. Each step should halve what\n   is left.\n3. **Explain it.** State the cause as a sentence with a mechanism: \"the cursor\n   carries a timestamp, Postgres keeps microseconds, JavaScript Date does not,\n   so rows sharing a millisecond are skipped.\" If you cannot write that sentence,\n   you have found a correlation, not a cause.\n4. **Fix the cause.** A fix that makes the symptom go away without explaining it\n   moves the defect rather than removing it.\n5. **Prove it.** Write a test that fails before the fix and passes after. Run it\n   both ways round — a test that never failed proves nothing.\n\n## When you are stuck\n\n- Check your assumptions one at a time, cheapest first. Print the value you are\n  certain about; it is often the one that is wrong.\n- Read the error text literally, including the parts you think you understand.\n- Look at what changed. If it worked last week, something is different.\n- Reproduce it in isolation, outside the application. Most \"framework bugs\" stop\n  reproducing at that point, and the ones that do not are worth reporting.\n\n## Do not\n\nDo not add a retry, a longer timeout, a null guard or a try/catch to make a\nsymptom stop, unless you can say why the underlying condition is legitimate.\nSilencing an error deletes the evidence for whoever meets it next.\n",
  },
  {
    slug: "performance-work",
    category: "engineering",
    markdown: "---\nname: performance-work\ndescription: Make something faster, with evidence that it was slow and evidence that it is not any more. Use when latency, cost or throughput is a stated problem.\nrecommendedForRoles:\n  - engineer\n  - devops\ntags:\n  - performance\n  - engineering\n---\n\n# Performance work\n\nOptimisation without measurement is decoration.\n\n## Order\n\n1. **State the target.** \"The report page takes 9 seconds and should take under\n   2\" is a target. \"Make it faster\" is not.\n2. **Measure where the time goes.** Profile, trace, or time the stages. Do not\n   guess: the slow part is routinely not the part everybody blames.\n3. **Fix the biggest thing.** A 90% improvement on 3% of the time is nothing.\n4. **Measure again** on the same workload. Keep the before and after numbers.\n5. **Stop** when you hit the target. Past that you are spending time nobody asked\n   you to spend.\n\n## Where the time usually is\n\n- **Queries in a loop.** One query per row, called from a template. Look for this\n  first; it is the most common and the easiest to fix.\n- **A missing index.** Read the query plan, do not assume. A sequential scan on a\n  large table is visible immediately.\n- **Fetching more than you show.** Selecting every column and every row to\n  display twenty.\n- **Work done repeatedly** that could be done once, or at write time instead of\n  read time.\n- **Serial round trips** that could be concurrent.\n\n## Measure honestly\n\n- Use a realistic data volume. Everything is fast with a hundred rows.\n- Report a percentile, not an average. An average hides the slow tail, and the\n  slow tail is what people complain about.\n- Warm the cache the same way in both runs, or neither.\n\n## Before adding a cache\n\nA cache is a correctness problem you are choosing to take on: staleness,\ninvalidation, and a second source of truth. Exhaust the cheaper fixes first — an\nindex, a smaller query, removing the loop — and when you do add one, decide how\nit is invalidated before you write it.\n",
  },
  {
    slug: "refactoring",
    category: "engineering",
    markdown: "---\nname: refactoring\ndescription: Change the shape of code without changing what it does. Use when code is hard to work with and the behaviour must stay identical.\nrecommendedForRoles:\n  - engineer\n  - cto\ntags:\n  - refactoring\n  - engineering\n---\n\n# Refactoring\n\nRefactoring changes structure and nothing else. The moment behaviour changes, it\nis not a refactor any more — it is a change, and it needs the scrutiny of one.\n\n## Before you start\n\n- **Have tests.** Without them you cannot tell a refactor from a rewrite. If\n  there are none, write characterisation tests first: capture what the code does\n  now, including the parts that look wrong.\n- **Know why.** \"Cleaner\" is not a reason. A reason is: this is the third time\n  this week somebody has had to change the same thing in four places.\n\n## How\n\n1. One transformation at a time. Rename, or extract, or move — not all three.\n2. Run the tests after each one.\n3. Commit each step separately, so a mistake can be undone without losing the rest.\n\n## Keep separate\n\nNever mix a refactor with a behaviour change in one commit. When a reviewer has\nto read four hundred moved lines to find the two that changed, they will not find\nthem. Move first, change second, in two commits.\n\n## When to stop\n\nStop when the thing you wanted to do next is easy. Refactoring is not an end in\nitself, and a codebase can be polished long past the point where anybody\nbenefits.\n\n## Worth doing\n\n- The same change having to be made in several places.\n- A function whose name and behaviour have drifted apart.\n- A conditional nobody can read, guarding something simple.\n- Duplication that has been copied a third time.\n\n## Not worth doing\n\n- Code nobody is going to touch again.\n- Style that differs from your preference but is consistent with its neighbours.\n- Anything you cannot test.\n",
  },
  {
    slug: "writing-tests",
    category: "engineering",
    markdown: "---\nname: writing-tests\ndescription: Decide what to test and write tests that catch real defects. Use when adding a feature, fixing a bug, or finding existing tests that pass while the code is broken.\nrecommendedForRoles:\n  - engineer\n  - qa\ntags:\n  - testing\n  - quality\n---\n\n# Writing tests\n\nA test earns its place by failing when the code is wrong.\n\n## What to test\n\nTest **behaviour and invariants**, not implementation. A test pinned to the exact\nwords of a message breaks on every honest rewrite; a test that asserts the\naffordance exists survives it.\n\nCover, in this order:\n\n1. **The contract** — the thing the code promises for ordinary input.\n2. **The boundaries** — zero, one, many; empty, missing, maximum; first and last.\n3. **The failure paths** — every error the function can return, and what state is\n   left behind when it does.\n4. **The invariant** — the thing that must be true no matter the order of events.\n   These are the tests worth the most and the ones most often missing.\n\n## Regression tests\n\nEvery bug fixed gets a test that fails without the fix. Name it for the\nbehaviour, not the ticket, and put a comment above it saying what went wrong —\nthe next person to see it fail needs to know what it is protecting.\n\n## Make it fail first\n\nRun a new test against the unfixed code and watch it fail. A test that has never\nfailed is an assertion about nothing. When you cannot easily do that, change the\nexpected value, confirm it fails, and change it back.\n\n## Concurrency and isolation\n\nRace conditions need a real concurrent test — two calls in flight at once — not a\nmock that returns in a fixed order. Data isolation needs a real second tenant,\nnot a stubbed permission check.\n\n## Signs of a bad test\n\n- It passes when you break the code.\n- It fails when you rename something private.\n- It depends on state another test left behind.\n- It asserts on a log line, a timestamp, or the order of an unordered collection.\n",
  },
  {
    slug: "competitor-analysis",
    category: "marketing",
    markdown: "---\nname: competitor-analysis\ndescription: Work out what competitors actually do and what it means for your decisions. Use when positioning a product, planning a roadmap, or entering a market.\nrecommendedForRoles:\n  - cmo\n  - ceo\n  - pm\n  - researcher\ntags:\n  - research\n  - marketing\n  - strategy\n---\n\n# Competitor analysis\n\nThe point is a decision, not a spreadsheet. Start from the decision.\n\n## When to use\n\nPositioning, pricing, prioritising a roadmap, or deciding whether to enter a\nmarket.\n\n## Start with the question\n\nWrite down what you will do differently depending on the answer. \"How do we\nposition against X\" or \"should we build Y\". An analysis without a decision\nattached becomes a document nobody opens twice.\n\n## Where the truth is\n\nRanked by how much it tells you:\n\n1. **Use the product.** Sign up, complete the core job, try to cancel. Half an\n   hour here beats a day of reading.\n2. **Their pricing page** — what they charge, what they gate, who they are built\n   for. Pricing reveals the strategy more honestly than the marketing does.\n3. **Their changelog and job listings** — what they are building, and where they\n   are investing next.\n4. **Reviews and support forums** — what customers actually complain about. The\n   gap between the marketing and the complaints is the opportunity.\n5. **Their documentation** — the real capabilities, without the adjectives.\n\n## What to compare\n\nOnly what matters to a customer choosing. A feature grid with forty rows says\neverything is equally important, which is false and hides the three that decide\nit.\n\nFor each: what they do well, what they do badly, who they are genuinely best for.\nA competitor with no strengths means you have not looked properly.\n\n## Be honest\n\nWrite down where they are better. An analysis that concludes you win on every\naxis is worthless as an input to a decision, and everybody reading it knows it.\n",
  },
  {
    slug: "content-brief",
    category: "marketing",
    markdown: "---\nname: content-brief\ndescription: Turn a topic into a brief a writer can execute without asking questions. Use when commissioning an article, a guide, or a piece of campaign content.\nrecommendedForRoles:\n  - cmo\n  - researcher\n  - general\ntags:\n  - content\n  - marketing\n  - writing\n---\n\n# Content brief\n\nThe brief is where a piece is won or lost. A vague brief produces a piece nobody\nwanted, and the revision costs more than the writing did.\n\n## When to use\n\nCommissioning or planning any substantial piece of content.\n\n## What a brief contains\n\n1. **The reader.** Who, what they already know, what they are trying to do.\n   \"Marketers\" is not a reader; \"a marketer at a 20-person company who has never\n   run a paid campaign\" is.\n2. **The one question the piece answers.** If there are three, it is three pieces.\n3. **What the reader can do differently afterwards.** A piece that changes nothing\n   is entertainment, which is a valid goal but a different one.\n4. **The angle** — why this piece rather than the ten that already exist. Read\n   the top results before writing the brief; if you cannot say what yours adds,\n   do not commission it.\n5. **The structure** — the sections, in order, with a line on each.\n6. **Evidence required** — the data, examples, or sources that must appear.\n   Content that asserts without evidence is content nobody links to.\n7. **Constraints** — length, tone, what to avoid, who reviews it.\n\n## What to leave out\n\nDo not write the piece in the brief. Specifying every sentence produces a worse\nresult than specifying the shape and letting the writer write.\n\n## Distribution before commissioning\n\nDecide where it will be published and how people will find it before it is\nwritten. A good piece nobody reads is a failure of planning, not of writing.\n",
  },
  {
    slug: "email-campaigns",
    category: "marketing",
    markdown: "---\nname: email-campaigns\ndescription: Plan and write email that people open, read and act on. Use when writing a campaign, a lifecycle sequence, or a product announcement.\nrecommendedForRoles:\n  - cmo\n  - general\ntags:\n  - email\n  - marketing\n  - copywriting\n---\n\n# Email campaigns\n\nThe only email worth sending is one somebody would be annoyed to have missed.\n\n## When to use\n\nWriting a campaign, an onboarding sequence, an announcement, or a newsletter.\n\n## Before writing\n\n- **Who is on this list, and why did they join?** An email that ignores the\n  reason they subscribed is the one that gets unsubscribed.\n- **What is the single action?** One per email.\n- **What happens if they ignore it?** If nothing, consider not sending it.\n\n## The parts, in the order they are judged\n\n1. **From** — a name people recognise. This decides more opens than anything else.\n2. **Subject** — specific, honest, short. Say what is inside. Curiosity gaps and\n   false urgency work once and cost you the list.\n3. **First line** — visible in the preview, so it is part of the subject in\n   practice. Do not waste it on a greeting.\n4. **Body** — one idea. Short paragraphs. The action visible without scrolling.\n5. **One call to action**, as a link somebody can find while skimming.\n\n## Sequences\n\nMap what the reader knows at each step and write the next email for that person,\nnot for a new subscriber. The most common failure in a lifecycle sequence is\nevery email being written as though it is the first.\n\nSend fewer than you can. Frequency is the most reliable way to destroy a list.\n\n## Measure the right thing\n\nOpens are unreliable and getting worse. Judge by the action taken, and by\nunsubscribes — a campaign with a good click rate and a spike in unsubscribes cost\nmore than it earned.\n",
  },
  {
    slug: "landing-page-copy",
    category: "marketing",
    markdown: "---\nname: landing-page-copy\ndescription: Write a landing page that says what the thing is and why it matters. Use when launching a product or feature, or rewriting a page that does not convert.\nrecommendedForRoles:\n  - cmo\n  - general\ntags:\n  - copywriting\n  - marketing\n  - conversion\n---\n\n# Landing page copy\n\nSomebody arrives knowing nothing and leaves in about eight seconds unless you\ngive them a reason not to.\n\n## When to use\n\nWriting or rewriting a page whose job is to get one specific action.\n\n## Before writing a word\n\nAnswer three questions and write the answers down:\n\n- **Who is this for?** Not \"businesses\". A person, with a job and a problem.\n- **What is the problem, in their words?** Use words they would say, not the ones\n  your industry uses.\n- **What is the one action?** One. A page with four equally weighted calls to\n  action gets fewer of all of them.\n\n## The page\n\n- **Headline** — what it is and who it is for, in one line. Not a slogan. If a\n  reader cannot tell what the product does from the headline alone, it is wrong.\n- **Subhead** — how it works, in a sentence.\n- **Proof, immediately** — a screenshot of the real thing, a number, a named\n  customer. A page that asks for belief without evidence gets none.\n- **The specific benefits** — three or four, each concrete. \"Cuts invoice\n  processing from two days to ten minutes\", not \"streamlines your workflow\".\n- **Objections** — the reasons people do not buy, answered plainly. Price,\n  migration, lock-in, security. Avoiding them does not make them go away.\n- **One call to action**, repeated, saying what happens next.\n\n## Rules\n\n- Cut every sentence that would survive being said about a competitor. If it is\n  true of everyone it says nothing.\n- No adjective without evidence behind it.\n- Write the way somebody would explain it to a colleague, out loud.\n- Say what it costs. A page that hides pricing loses the people who would have\n  paid and wastes the time of those who would not.\n",
  },
  {
    slug: "seo-audit",
    category: "marketing",
    markdown: "---\nname: seo-audit\ndescription: Audit a site for the things that actually affect search visibility. Use when traffic is flat or falling, or before publishing a new site section.\nrecommendedForRoles:\n  - cmo\n  - researcher\n  - general\ntags:\n  - seo\n  - marketing\n  - audit\n---\n\n# SEO audit\n\nMost SEO advice is noise. A small number of things move the result.\n\n## When to use\n\nOrganic traffic is flat or falling, a new section is about to launch, or a\nmigration is planned.\n\n## Order, by what it costs when wrong\n\n1. **Can it be crawled and indexed?** `robots.txt`, `noindex` tags, canonical\n   tags pointing somewhere wrong, pages reachable only by a script. A page that\n   cannot be indexed cannot rank, and this is where catastrophic mistakes live —\n   a `noindex` left on after a staging deploy costs everything.\n2. **Is there one URL per thing?** Duplicates with tracking parameters, both\n   trailing-slash forms, both protocols, both www forms. Pick one, redirect the\n   rest permanently, and set canonicals.\n3. **Does each page answer one question?** Title and heading matching what\n   somebody actually searched, and content that answers it in the first screen.\n4. **Is it fast on a phone?** Largest contentful paint and layout shift, measured\n   on real devices rather than a desktop lab run.\n5. **Internal links.** A page nothing links to is a page that will not rank.\n   Link from related pages with the words people search for.\n\n## What to ignore\n\nKeyword density, meta keywords, exact-match anchor text everywhere, and anything\npromising a specific rank. They do not work and some are penalised.\n\n## Migrations\n\nThe single biggest risk. Map every old URL to a new one, redirect permanently\nwith a 301, and keep them for years. Check the map before launch and the error\nlogs for weeks after.\n\n## Report it\n\nPer finding: the pages affected, the evidence, the estimated impact, and the fix.\nOrder by impact, not by ease.\n",
  },
  {
    slug: "ci-cd-pipelines",
    category: "operations",
    markdown: "---\nname: ci-cd-pipelines\ndescription: Build and maintain a pipeline that tells the truth quickly. Use when setting up CI, adding checks, or diagnosing a pipeline nobody trusts.\nrecommendedForRoles:\n  - devops\n  - engineer\ntags:\n  - ci\n  - automation\n  - operations\n---\n\n# CI and CD pipelines\n\nA pipeline has one job: tell you whether this change is safe, before anybody\nelse finds out it was not.\n\n## When to use\n\nSetting up continuous integration, adding a gate, or fixing a pipeline that is\nslow, flaky, or routinely ignored.\n\n## What it must do\n\n- **Run on every change**, in a clean environment, from a checkout — not from\n  whatever happened to be on the machine.\n- **Be deterministic.** The same commit gives the same result. Pin versions; do\n  not resolve a dependency range at build time.\n- **Be fast enough to wait for.** Past about ten minutes people stop watching and\n  start merging on hope. Cache dependencies, run independent jobs in parallel,\n  and run the cheapest checks first so an obvious failure fails in seconds.\n- **Fail for one reason at a time.** A job that runs lint, tests and a build in\n  one step makes you read the log to find out which broke.\n\n## Flaky tests\n\nA test that fails one run in twenty is worse than no test: it teaches everybody\nto re-run without reading. Quarantine it the day you notice, and either fix it or\ndelete it that week. Do not add an automatic retry — that is how a real\nintermittent bug stays hidden for a year.\n\n## Deploying\n\n- Build the artefact once and promote the same bytes through environments. Do not\n  rebuild per environment.\n- Every deploy has a rollback that has been tried, not assumed.\n- Secrets come from the environment, never from the repository. A credential in a\n  build log is a leaked credential.\n\n## Signs it is not working\n\nPeople re-run failed jobs without looking. The pipeline is red on the main branch\nand nobody is alarmed. Anyone says \"that check always fails.\"\n",
  },
  {
    slug: "containers",
    category: "operations",
    markdown: "---\nname: containers\ndescription: Build small, reproducible container images and run them safely. Use when writing a Dockerfile, debugging an image, or reviewing container configuration.\nrecommendedForRoles:\n  - devops\n  - engineer\ntags:\n  - docker\n  - containers\n  - operations\n---\n\n# Containers\n\nAn image should be small, reproducible, and contain nothing it does not need.\n\n## When to use\n\nWriting or reviewing a Dockerfile, or diagnosing why an image is enormous, slow\nto build, or behaves differently from the developer machine.\n\n## Building\n\n- **Pin the base image** to a digest, not `latest`. `latest` means your build is\n  not reproducible and can change under you overnight.\n- **Multi-stage.** Compile in one stage, copy only the artefact into a minimal\n  runtime stage. Build tools in a production image are both weight and attack\n  surface.\n- **Order layers by how often they change.** Dependency manifests and install\n  first, application source last — otherwise every source edit reinstalls\n  everything.\n- **Use `.dockerignore`.** Without it the whole working directory, including\n  `.git` and local secrets, goes into the build context.\n\n## Running\n\n- **Not as root.** Create a user and switch to it.\n- **Read-only filesystem** where you can, with explicit writable volumes.\n- **Set resource limits.** An unbounded container will take the node down with it.\n- **Configuration through environment**, state through volumes. An image should\n  be identical in every environment.\n- **One concern per container.** If you are running a supervisor inside, you\n  probably want two containers.\n\n## Health\n\nGive it a health check that tests the thing it does, not just that the process is\nalive. A process that is running but cannot reach its database is not healthy,\nand the orchestrator cannot know that unless you tell it.\n\n## Secrets\n\nNever in `ENV` in the Dockerfile, never in a layer. Anything written into a layer\nstays in the image history even if a later layer deletes it.\n",
  },
  {
    slug: "incident-response",
    category: "operations",
    markdown: "---\nname: incident-response\ndescription: Run a live incident: stop the bleeding first, find the cause afterwards. Use when something is broken in production and users are affected.\nrecommendedForRoles:\n  - devops\n  - engineer\n  - cto\ntags:\n  - incident\n  - operations\n  - reliability\n---\n\n# Incident response\n\nRestore service first. Understanding comes second, and it comes better with the\npressure off.\n\n## When to use\n\nSomething in production is failing or degraded and people are affected right now.\n\n## When not to use\n\nA defect nobody is hitting yet. That is a bug report, and it goes through the\nordinary queue.\n\n## Order\n\n1. **Declare it.** Say out loud that this is an incident and who is running it.\n   Ambiguity about whether anything is happening costs more time than the fix.\n2. **Assess.** What is broken, for whom, since when, how badly. Write it in one\n   sentence and keep that sentence updated — it is what everyone else reads.\n3. **Mitigate.** Roll back, fail over, disable the feature, shed load. Mitigation\n   is not the fix and does not need to be elegant. If a rollback is available and\n   plausible, do it before diagnosing further.\n4. **Verify** the mitigation with the same signal that told you it was broken.\n5. **Then** diagnose, at your own pace, with the incident closed.\n\n## While it is running\n\n- One person decides. Others investigate and report.\n- Keep a timestamped log of what you observed and what you changed. Memory\n  afterwards is unreliable and the log becomes the review.\n- Change one thing at a time. Two simultaneous changes and you will not know\n  which worked.\n- Say what you do not know. \"I do not yet know whether this is the cause\" is more\n  useful than a confident guess.\n\n## Afterwards\n\nWrite it up while it is fresh: timeline, impact, what actually caused it, what\nmade it take as long as it did to notice and to fix. Look for the missing signal\nand the missing guardrail. Blame the system, not the person who pressed the\nbutton — the system let them.\n",
  },
  {
    slug: "infrastructure-as-code",
    category: "operations",
    markdown: "---\nname: infrastructure-as-code\ndescription: Define infrastructure in version-controlled code so environments are reproducible. Use when provisioning or changing cloud resources.\nrecommendedForRoles:\n  - devops\n  - engineer\ntags:\n  - infrastructure\n  - terraform\n  - operations\n---\n\n# Infrastructure as code\n\nIf it was created by clicking, it cannot be reviewed, reproduced, or restored.\n\n## When to use\n\nProvisioning or changing any long-lived infrastructure: networks, databases,\nqueues, clusters, DNS, permissions.\n\n## Rules\n\n- **Everything in version control**, reviewed like application code. An\n  unreviewed infrastructure change is the one that opens a database to the\n  internet.\n- **Plan before apply, every time.** Read the plan. A change that says it will\n  destroy and recreate a database is a change to stop.\n- **State is precious.** Store it remotely, locked, versioned and backed up.\n  A lost or corrupted state file is a very bad day.\n- **No manual edits.** A resource changed by hand drifts from the code, and the\n  next apply either reverts it or fails. If you must touch something live during\n  an incident, put it back into code the same day.\n\n## Structure\n\nSeparate environments completely — different state, different credentials. A\ntypo should not be able to reach production from a development change.\n\nPrefer many small modules with clear inputs to one large configuration. Keep the\nblast radius of any single apply small.\n\n## Secrets\n\nNever in the repository, never in state you have not encrypted. Use the secret\nmanager the platform provides, and reference it.\n\n## Destructive changes\n\nKnow which attribute changes force replacement before you propose them. For\nanything stateful, take a backup first and say in the change description what the\nrecovery plan is.\n",
  },
  {
    slug: "observability",
    category: "operations",
    markdown: "---\nname: observability\ndescription: Instrument a system so failures explain themselves. Use when adding logging, metrics or tracing, or when an outage was hard to diagnose.\nrecommendedForRoles:\n  - devops\n  - engineer\n  - cto\ntags:\n  - observability\n  - monitoring\n  - operations\n---\n\n# Observability\n\nThe test is simple: when something breaks at three in the morning, can somebody\nfind out why without adding code?\n\n## When to use\n\nAdding instrumentation, choosing what to alert on, or reviewing why a past\nincident took too long to diagnose.\n\n## The three, and what each is for\n\n- **Logs** — what happened in one request. Structured key-value, not prose.\n  Include a request id on every line so one journey can be followed end to end.\n- **Metrics** — how the system behaves in aggregate, over time. Cheap, sampled,\n  good for \"is it getting worse\".\n- **Traces** — where the time went across services in one request. The only one\n  that answers \"which hop is slow\".\n\n## What to record\n\nFor every external call and every unit of work: what was attempted, whether it\nsucceeded, how long it took, and enough identity to find the row afterwards.\n\nFor every error: the error, the input that caused it, and the context to\nreproduce it. An error log with no identifiers tells you something is wrong and\nnothing else.\n\n## Never log\n\nPasswords, tokens, keys, full card numbers, personal data you would not put in an\nemail. Redact at the point of writing, not in a later pipeline — the pipeline\nwill be misconfigured one day.\n\n## Alerts\n\nAlert on symptoms users feel: error rate, latency, queue depth, failed\ntransactions. Do not alert on causes — CPU at 90% is fine if nobody notices.\n\nEvery alert must be actionable and documented: what it means, what to check, what\nto do. An alert nobody acts on trains people to ignore the whole channel, which\ncosts you the one that mattered.\n",
  },
  {
    slug: "release-and-rollback",
    category: "operations",
    markdown: "---\nname: release-and-rollback\ndescription: Ship a change to production and be able to undo it. Use when planning a deploy, a migration, or a risky feature launch.\nrecommendedForRoles:\n  - devops\n  - engineer\n  - cto\ntags:\n  - deployment\n  - release\n  - operations\n---\n\n# Release and rollback\n\nEvery release is a bet. The question is what it costs when you are wrong.\n\n## When to use\n\nPlanning any deploy that could affect users: a feature launch, a schema change, a\ndependency upgrade, a configuration change.\n\n## Before\n\n- **Know how to undo it**, and have tried. An untested rollback is a hope.\n- **Separate the risky part.** A release with a migration, a feature and a\n  refactor in it cannot be partially rolled back. Ship them in separate releases.\n- **Decide what \"it went wrong\" looks like** — which metric, what threshold, how\n  long you watch. Decide it beforehand, because afterwards everyone will argue\n  about whether the graph is bad.\n\n## Strategies, and when each fits\n\n- **Rolling** — replace instances gradually. Fine for a stateless change with a\n  compatible API.\n- **Blue-green** — run both, switch traffic, keep the old one warm. Fast\n  rollback, double the resources for a while.\n- **Canary** — a small share of traffic first, watched, then widened. Best for\n  anything where you are unsure, and the only one that finds problems that need\n  real traffic to appear.\n- **Feature flag** — ship the code dark, turn it on separately. Decouples deploy\n  risk from release risk, and gives an instant off switch that needs no deploy.\n\n## Data\n\nCode can roll back. Data usually cannot. A migration that drops a column cannot\nbe undone by redeploying yesterday's build — so never destroy data in the same\nrelease that stops using it. Expand, migrate, then contract, in separate releases\nwith time between them.\n\n## After\n\nWatch for longer than feels necessary. The failures that matter are often not\nimmediate: a slow leak, a queue filling, a nightly job meeting the new schema.\n",
  },
  {
    slug: "estimating-work",
    category: "product",
    markdown: "---\nname: estimating-work\ndescription: Produce an estimate that is useful rather than confidently wrong. Use when asked how long something will take, or when planning a sequence of work.\nrecommendedForRoles:\n  - pm\n  - cto\n  - engineer\ntags:\n  - planning\n  - estimation\n---\n\n# Estimating work\n\nAn estimate is a statement about uncertainty. Hiding the uncertainty is what\nmakes estimates useless.\n\n## When to use\n\nAnyone asks how long, or a plan needs an order and a shape.\n\n## How\n\n1. **Break it down** until each piece is something you have done something like\n   before. Anything you cannot break down is the thing you do not understand, and\n   that is where the risk is.\n2. **Estimate a range**, not a number. \"Three to eight days\" carries the\n   information \"one day\" does not.\n3. **Name what would make it the high end.** This is the most useful sentence in\n   any estimate, and it is often actionable — the unknown can be investigated\n   before committing.\n4. **Add the work that is always forgotten**: review, tests, the migration,\n   deployment, the documentation, fixing what review finds.\n\n## Spike the unknown\n\nWhen a piece is genuinely unknown, do not estimate it. Time-box an\ninvestigation — \"two days to find out whether this approach works\" — and\nre-estimate afterwards with what you learned. A guess about something nobody has\nlooked at is not improved by thinking harder about it.\n\n## Say it honestly\n\n- Distinguish an estimate from a commitment. They are different promises.\n- Give the assumptions. Most estimates are wrong because an assumption was.\n- Revise it when you learn something. An estimate held past the evidence is not\n  reliability, it is the opposite.\n",
  },
  {
    slug: "status-reporting",
    category: "product",
    markdown: "---\nname: status-reporting\ndescription: Write a status update that tells somebody what they need to decide. Use when reporting progress to a stakeholder, or summarising a body of work.\nrecommendedForRoles:\n  - pm\n  - ceo\n  - cto\n  - general\ntags:\n  - communication\n  - reporting\n---\n\n# Status reporting\n\nA status report exists so somebody can act. Write the part they would act on\nfirst.\n\n## When to use\n\nReporting progress on a project, a sprint, an incident, or a standing objective.\n\n## The shape\n\n1. **Where it stands** — one sentence. On track, at risk, or blocked, and by\n   when.\n2. **What changed since last time** — only what matters. Not a list of activity.\n3. **What needs a decision** — from whom, by when, and what happens if it does\n   not come. This is the section the report is for.\n4. **What is at risk** — with the specific thing that would have to happen.\n5. **What is done** — briefly, so nobody re-asks.\n\n## Rules\n\n- **Lead with bad news.** A report that buries a slip under three paragraphs of\n  progress destroys trust in every future report.\n- **Numbers with meaning.** \"14 of 20 closed\" is meaningful; \"significant\n  progress\" is not.\n- **Distinguish done from nearly done.** Nearly done is not done, and the last\n  ten per cent is routinely half the work.\n- **Name the risks you are carrying.** A risk somebody else finds out about\n  independently reads as concealment, even when it was only omission.\n- **Say what you do not know.** It is more useful than a confident guess and far\n  cheaper than being wrong.\n\n## Length\n\nIf it is longer than a screen, nobody reads past the first paragraph — so put\neverything that matters in the first paragraph, and treat the rest as reference.\n",
  },
  {
    slug: "technical-writing",
    category: "product",
    markdown: "---\nname: technical-writing\ndescription: Write documentation people can act on. Use when writing a README, a guide, release notes, or an explanation of how something works.\nrecommendedForRoles:\n  - pm\n  - engineer\n  - researcher\n  - general\ntags:\n  - writing\n  - documentation\n---\n\n# Technical writing\n\nDocumentation is read by somebody in a hurry who has a problem. Write for them.\n\n## When to use\n\nAny document whose purpose is to let somebody do something: a README, a runbook,\na guide, an API reference, release notes.\n\n## Decide which kind it is\n\nFour kinds, and mixing them is the most common failure:\n\n- **Tutorial** — teaches a beginner by having them do something that works. No\n  options, no alternatives, no explanation of internals.\n- **How-to** — solves one problem for somebody who already knows the basics.\n  Steps, in order.\n- **Reference** — describes what exists, accurately and exhaustively. Boring by\n  design. No narrative.\n- **Explanation** — why it works this way, what was considered instead.\n\nA README that tries to be all four teaches nobody and answers nothing.\n\n## Rules that matter most\n\n- **Start with what the reader wants to achieve**, not with what the thing is.\n- **Say what to do**, in the imperative. \"Run `x`\" not \"you may wish to run `x`\".\n- **Show the command and the expected output.** A step whose success cannot be\n  recognised is a step people get stuck on.\n- **State the prerequisites first**, so nobody gets three steps in before finding\n  out they need an account.\n- **Cut every sentence that does not change what the reader does.** Documentation\n  is not paid by the word.\n\n## Keep it true\n\nWrong documentation is worse than none — it costs the reader time and their\ntrust. When you change behaviour, change the document in the same commit. Date\nanything you cannot commit to keeping current.\n",
  },
  {
    slug: "writing-requirements",
    category: "product",
    markdown: "---\nname: writing-requirements\ndescription: Turn a request into work somebody can build and somebody else can verify. Use when given a vague ask, or before breaking a feature into tasks.\nrecommendedForRoles:\n  - pm\n  - cto\n  - ceo\ntags:\n  - product\n  - planning\n  - requirements\n---\n\n# Writing requirements\n\nA requirement that cannot be checked is an opinion.\n\n## When to use\n\nYou have been asked for something in one sentence and it needs to become work.\n\n## Start with the problem\n\nWrite down who has the problem, what they do today instead, and what it costs\nthem. If you cannot answer those, the answer is not a specification — it is a\nquestion for whoever asked.\n\nDo not start from a solution. \"Add a filter dropdown\" is a design decision\nwearing a requirement's clothes, and it forecloses better answers.\n\n## Then the shape\n\nFor each piece of work:\n\n- **What** — one sentence, in the user's terms, not the system's.\n- **Why** — the problem it solves. This is what lets somebody make a sensible\n  call when they hit an unexpected fork.\n- **Acceptance criteria** — checkable statements. Given this state, when this\n  happens, then this is true. Someone who did not write it must be able to test\n  it and get the same answer as you.\n- **Out of scope** — what this deliberately does not do. This prevents more\n  argument than anything else on the list.\n\n## Decisions, not wishes\n\nName the things that are genuinely undecided and decide them, or say who decides\nand by when. A specification full of \"TBD\" transfers the decision to whoever\nimplements it, at the worst possible moment.\n\n## Size\n\nIf it cannot be described in a page, it is more than one piece of work. Split it\nalong user-visible value, not along technical layers — \"the API part\" is not\nsomething anybody can accept.\n",
  },
  {
    slug: "accessibility-audit",
    category: "quality",
    markdown: "---\nname: accessibility-audit\ndescription: Check an interface against WCAG and against how people actually use assistive technology. Use when reviewing UI work or auditing an existing screen.\nrecommendedForRoles:\n  - qa\n  - designer\n  - engineer\ntags:\n  - accessibility\n  - design\n  - testing\n---\n\n# Accessibility audit\n\nAutomated tools catch perhaps a third of it. The rest needs a person.\n\n## Do these first, in order\n\n1. **Keyboard only.** Unplug the mouse. Can you reach everything, in a sensible\n   order? Is the focus always visible? Can you escape every dialog and menu? Does\n   focus return where it came from when one closes? A control you can reach but\n   not see focused is a control that is not usable.\n2. **Headings and landmarks.** One `h1`. No skipped levels. Real `nav`, `main`,\n   `header`. A screen reader user navigates by these before anything else.\n3. **Names.** Every control has an accessible name. An icon-only button needs\n   `aria-label`. Every input has a real `<label>`, not a placeholder standing in\n   for one.\n4. **Colour.** 4.5:1 for body text, 3:1 for large text and for the visual\n   boundary of a control. And nothing may be conveyed by colour alone — a red\n   border with no message is invisible to a third of colour-blind users.\n5. **Images.** Meaningful ones have alt text that says what they mean. Decorative\n   ones have `alt=\"\"`, not a filename.\n6. **Live changes.** Something that appears without a page load — a toast, a\n   validation error, a result count — needs an appropriate live region, or it\n   happens silently.\n\n## Forms specifically\n\nErrors must be associated with their field, described in text, and announced. An\nerror summary that says \"please fix the errors below\" helps nobody who cannot see\nbelow.\n\n## Motion and zoom\n\nRespect `prefers-reduced-motion`. Check the page at 200% zoom and at 400% — text\nmust reflow rather than being cut off or requiring horizontal scrolling.\n\n## Report it usefully\n\nFor each finding: the element, the guideline, who it affects and how, and the\nfix. \"Fails 1.4.3\" tells a developer nothing on its own.\n",
  },
  {
    slug: "bug-reporting",
    category: "quality",
    markdown: "---\nname: bug-reporting\ndescription: Write a defect report somebody can act on without asking you anything. Use whenever you find something broken and are handing it to someone else to fix.\nrecommendedForRoles:\n  - qa\n  - engineer\ntags:\n  - testing\n  - communication\n---\n\n# Bug reporting\n\nThe report is the deliverable. A defect nobody can reproduce is a defect nobody\nwill fix.\n\n## What every report needs\n\n1. **Title** — the symptom, specific. \"Empty password is accepted at the payment\n   step\", not \"login broken\".\n2. **Steps** — numbered, from a known starting state, with the exact values you\n   used. \"Enter a single space\" not \"enter something invalid\".\n3. **Expected** — what should have happened, and why you believe that.\n4. **Actual** — what did happen, quoted exactly. Include the error text verbatim.\n5. **Scope** — does it happen every time? On other browsers, other accounts,\n   other data? Where did you stop looking?\n6. **Evidence** — the request and response, the log line, the screenshot, the\n   commit you tested.\n\n## Severity, honestly\n\nSay what it costs, not how you feel about it. Data loss, a security hole and a\nmisaligned icon are three different things, and calling all of them urgent makes\nthe word useless.\n\n## Narrow it before you file it\n\nTwo minutes spent removing irrelevant steps saves an hour later. Try to make it\nfail with less: fewer steps, simpler data, a smaller account. If it stops\nfailing, you have learned something worth putting in the report.\n\n## Your verdict is the deliverable\n\nAn investigation that finds eleven defects **succeeded**. Report it as finished\nwork with an adverse result, not as a failure or a blockage. Blocked means you\ncould not proceed; it does not mean the news is bad.\n",
  },
  {
    slug: "exploratory-testing",
    category: "quality",
    markdown: "---\nname: exploratory-testing\ndescription: Hunt for defects without a script, in the places scripted tests do not reach. Use when asked to audit a feature deeply or to find what nobody thought to check.\nrecommendedForRoles:\n  - qa\ntags:\n  - testing\n---\n\n# Exploratory testing\n\nScripted tests check what somebody already thought of. This is for everything else.\n\n## Charters\n\nWork in short, named sessions with one question each, rather than wandering.\nA charter is: *explore [this area] with [these resources] to discover [this kind\nof information].* Time-box it, and write down what you find as you go.\n\n## Where defects hide\n\n- **Between features.** Each works alone; together they disagree about the same\n  data.\n- **The second time.** Do it twice. Do it twice quickly. Do it in two tabs.\n- **Going backwards.** Browser back, cancel halfway, refresh mid-operation, close\n  and return.\n- **The boundaries of the real world.** A name with an apostrophe, an emoji, a\n  right-to-left script. A number at zero and one below it. A date in February.\n- **Interruption.** Kill the network mid-request. Log out in another tab.\n- **Stale state.** A saved filter pointing at something deleted. A bookmark to a\n  page whose data has changed underneath it.\n- **Volume.** One row, and ten thousand. Empty, and full.\n\n## While you work\n\nVary one thing at a time, so you can say what caused what. When something looks\nodd, stop and pin it down before moving on — an oddity you cannot reproduce an\nhour later is lost.\n\nRecord everything, including the things that turned out to be fine. Coverage you\ncannot describe is coverage nobody can trust.\n",
  },
  {
    slug: "test-planning",
    category: "quality",
    markdown: "---\nname: test-planning\ndescription: Enumerate what to test before testing any of it, so nothing important is missed. Use when planning coverage for a feature, a release, or an audit.\nrecommendedForRoles:\n  - qa\n  - engineer\n  - pm\ntags:\n  - testing\n  - planning\n---\n\n# Test planning\n\nWrite the cases down first. A plan made while testing tests what was easy to\nreach.\n\n## Eight dimensions\n\nWork through all of them. Each case is one line: **input → expected**.\n\n1. **Normal flows** — the happy path, and the second and third visit, which are\n   different from the first.\n2. **Edge cases** — zero, one, very many. Empty, missing, maximum. A brand-new\n   account. A saved selection that no longer exists.\n3. **Invalid input** — bounds, wrong types, empty against null, hostile strings,\n   payloads far larger than expected.\n4. **Failure** — every error the dependency can return, timeouts, malformed\n   responses, a batch that half-succeeds, no network at all.\n5. **Permissions** — signed out, wrong tenant, each role, an entitlement that\n   expired, an identifier guessed from another account.\n6. **State transitions** — loading to data to empty to error to retry. What a\n   background job does to a screen somebody is looking at.\n7. **Races** — two tabs, a double submit, rapid switching, responses arriving out\n   of order, two writers on one row.\n8. **Regressions** — everything already asserted about this area, plus every\n   other caller of anything shared you touched.\n\n## Then\n\nMark each case: verified, failed, or **untested**. Untested is a real outcome —\nrecord what it needed that you did not have. Quietly dropping a case you could\nnot run is how a gap becomes a surprise.\n\n## Sizing\n\nNot every dimension deserves equal weight. Spend it where a defect would cost\nmost: data loss, money, access to somebody else's information. A cosmetic\nregression on a rarely used screen is worth one line, not ten.\n",
  },
  {
    slug: "secrets-and-credentials",
    category: "security",
    markdown: "---\nname: secrets-and-credentials\ndescription: Handle keys, tokens and passwords so they do not leak, and respond when one does. Use when adding a credential, reviewing configuration, or after a suspected exposure.\nrecommendedForRoles:\n  - security\n  - devops\n  - engineer\ntags:\n  - security\n  - secrets\n---\n\n# Secrets and credentials\n\nAssume every secret will eventually be read by someone who should not have it.\nDesign for how much that costs.\n\n## When to use\n\nAdding or rotating any credential, reviewing configuration, or responding to a\nsuspected leak.\n\n## Rules\n\n- **Never in the repository.** Not in code, not in configuration, not in a test\n  fixture, not commented out. Git keeps it for ever, and history is public the\n  moment the repository is.\n- **Environment or secret manager**, injected at run time.\n- **Never in an argument list.** Process arguments are readable by every user on\n  the machine. Environment or a file with narrow permissions.\n- **Never in a log**, an error message, a client bundle, or a transcript. Redact\n  where it is written, not downstream.\n- **Scope it.** A token that can do one thing costs one thing when it leaks.\n- **Expire it.** A short-lived credential limits the window; a permanent one is a\n  permanent liability.\n\n## Rotation\n\nRotating should be routine, not an emergency procedure performed for the first\ntime during an emergency. It needs to work without downtime, which means the\nsystem must accept the old and the new at once for a period.\n\n## When one leaks\n\n1. **Revoke first.** Before investigating, before telling anyone, before working\n   out how bad it is. Revocation is cheap; the window is not.\n2. Issue a replacement and deploy it.\n3. Then find out what it could reach and whether it was used. Check the access\n   logs for the whole period it was exposed, not just since you noticed.\n4. Rewriting git history does not help — assume anything pushed was cloned.\n",
  },
  {
    slug: "secure-code-review",
    category: "security",
    markdown: "---\nname: secure-code-review\ndescription: Read code specifically for vulnerabilities rather than for correctness. Use when reviewing anything that handles input, authentication, or sensitive data.\nrecommendedForRoles:\n  - security\n  - engineer\ntags:\n  - security\n  - review\n---\n\n# Secure code review\n\nAn ordinary review asks whether the code does what it should. This one asks what\nelse it can be made to do.\n\n## When to use\n\nAny change touching authentication, authorisation, user input, file handling,\nserialisation, or a third-party integration.\n\n## Follow the input\n\nStart at every place data enters — request bodies, query strings, headers,\ncookies, file uploads, webhooks, message queues, anything a model produced — and\nfollow each one to where it is used. Vulnerabilities live at the destination.\n\nCheck at each destination:\n\n- **A query** — is it parameterised? String concatenation into SQL, a shell\n  command, an LDAP filter or a template is the whole bug.\n- **A response** — is it escaped for where it lands? HTML, an attribute, a URL\n  and JavaScript each need different escaping.\n- **A path** — can it escape the directory? `../`, an absolute path, a symlink.\n- **A URL the server fetches** — can it be pointed at internal addresses?\n- **Deserialisation** — can it construct arbitrary objects?\n\n## Authorisation\n\nThe most common serious defect is not a missing check but a check in one place\nand not another. For every resource, ask: is authorisation enforced on every\nroute that reaches it, including list endpoints, exports, and the one added last\nweek? Is it enforced by identity from the session, or by an id from the request?\n\nAn id from the request that is trusted is how one customer reads another's data.\n\n## Secrets and errors\n\nLook for credentials in code, in logs, in error responses, in client bundles.\nCheck that failures do not disclose whether a record exists, and that a resource\nin another tenant answers not-found rather than forbidden.\n\n## Report it\n\nName the input, the path it takes, and what an attacker gets. A finding without\nthose three is a suggestion.\n",
  },
  {
    slug: "threat-modelling",
    category: "security",
    markdown: "---\nname: threat-modelling\ndescription: Work out what an attacker would try before they try it. Use when designing a feature that handles money, personal data, authentication or third-party input.\nrecommendedForRoles:\n  - security\n  - engineer\n  - cto\ntags:\n  - security\n  - design\n---\n\n# Threat modelling\n\nFour questions, in order. Most of the value is in the first.\n\n## When to use\n\nDesigning anything that touches authentication, authorisation, money, personal\ndata, file uploads, or content from outside your system.\n\n## The questions\n\n1. **What are we building?** Draw the data flow: what enters, what stores it,\n   what reads it, and where the trust boundaries are. Most missed vulnerabilities\n   are missed because nobody drew this.\n2. **What can go wrong?** Walk each boundary. Who can reach it? What do they\n   control? What happens if they send something hostile, something enormous, or\n   the same thing a thousand times?\n3. **What are we doing about it?** For each, decide: mitigate, accept, or\n   transfer. Write the decision down — an accepted risk that nobody recorded\n   looks like an oversight later.\n4. **Did we do a good job?** Review it when the design changes.\n\n## Prompts that find real things\n\n- **Spoofing** — can somebody act as another user or service?\n- **Tampering** — can they change data in transit or at rest?\n- **Repudiation** — could someone deny doing it, and would we be able to show\n  otherwise?\n- **Information disclosure** — what leaks in errors, logs, timing, or a 403 that\n  should be a 404?\n- **Denial of service** — what is unbounded? Request size, result set, retries,\n  file upload, regex.\n- **Elevation of privilege** — where is authorisation checked, and is it checked\n  on every path or only the one through the UI?\n\n## Rank honestly\n\nOrder by what it would cost and how easily it can be reached. An unauthenticated\ndata leak beats a theoretical attack requiring physical access, however clever\nthe second one is.\n",
  },
  {
    slug: "breaking-down-work",
    category: "teamwork",
    markdown: "---\nname: breaking-down-work\ndescription: Split a large piece of work into tasks that can be done independently and finished. Use when planning a feature, or when a task is too big to start.\nrecommendedForRoles:\n  - pm\n  - cto\n  - engineer\n  - ceo\ntags:\n  - planning\n  - delegation\n  - teamwork\n---\n\n# Breaking down work\n\nA good breakdown means somebody can pick up any piece and finish it without\nasking you.\n\n## When to use\n\nA piece of work is too large to start, or needs to be shared between several\npeople or agents.\n\n## Split by value, not by layer\n\n\"The API part\" and \"the UI part\" cannot be finished, demonstrated, or accepted on\ntheir own, and neither is done until both are. Split along things a user could\nnotice: one behaviour, end to end, however small.\n\nThe exception is when one piece genuinely blocks another and can be finished\nfirst — then say so explicitly as a dependency, rather than leaving it implied.\n\n## What each piece needs\n\n- **One sentence** of what it is, in the user's terms.\n- **Enough context to start.** Assume the person picking it up was not in the\n  conversation where it was decided.\n- **A way to tell it is finished.** Checkable by somebody who did not do it.\n- **Its dependencies**, named. \"Cannot start until X\" is information; discovering\n  it halfway through is a wasted day.\n\n## Size\n\nSmall enough to finish in one sitting, large enough to be worth handing over.\nToo big and it stalls invisibly; too small and coordinating them costs more than\ndoing them.\n\n## Signs it is wrong\n\n- Two pieces that have to be done by the same person at the same time. That is one\n  piece.\n- A piece nobody can start until three others finish. Sequence them, or find the\n  independent part.\n- A piece whose description is a technical instruction. That means the decision\n  was already made and the breakdown is a to-do list, not a plan.\n",
  },
  {
    slug: "handing-work-over",
    category: "teamwork",
    markdown: "---\nname: handing-work-over\ndescription: Give work to somebody else so they can start immediately and finish without you. Use when delegating a task, requesting a review, or passing work between agents.\nrecommendedForRoles:\n  - pm\n  - cto\n  - engineer\n  - qa\n  - general\ntags:\n  - delegation\n  - communication\n  - teamwork\n---\n\n# Handing work over\n\nThe handover is the work. A task somebody has to come back and ask about was not\ndelegated, it was announced.\n\n## When to use\n\nGiving a task to another person or agent, requesting a review, or returning work\nthat needs changes.\n\n## What travels with it\n\n- **What is needed**, in one sentence, as an outcome rather than an instruction.\n- **Why** — enough that they can make a sensible decision at a fork you did not\n  anticipate. This is the part most often left out and the part that most often\n  causes the wrong thing to be built.\n- **What you already know** — what you tried, what you ruled out, where the\n  relevant code or document is. Every minute of context you write saves an hour\n  of rediscovery.\n- **How anyone will know it is done.** Checkable, by them, without you.\n- **What is out of scope**, if there is an obvious adjacent thing you do not want\n  done.\n\n## Pick the right person\n\nBy what the work needs, not by who is free. Handing a security review to whoever\nhas capacity produces a review-shaped object.\n\n## Returning work\n\nWhen sending something back, the reason is the entire value of the message. Say\nwhat is wrong, how you found it, and what would make it right. \"Doesn't work\" is\nnot a reason; \"a single space still passes because the check is `!password` and\nshould be `!password.trim()`\" is a fix.\n\n## Do not\n\nDo not hand back work to somebody who is already waiting on you for something\nelse in the same chain — that is a loop, and both halves will sit there. Resolve\nyour own part first, or hand it to a third person.\n",
  },
];
